# This is a basic workflow to help you get started with Actions

name: generate-aio

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4       
        with:
          ref: ${{ github.head_ref }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo '// ********************************************************************************************************************************' >> exotic-class-item-aio.txt
          echo '// This file is auto-generated based on a GitHub workflow. Any and all changes should be made to the individual class item files.
          echo '// ********************************************************************************************************************************' >> exotic-class-item-aio.txt
          echo 'title: Exotic Class Items' > exotic-class-item-aio.txt
          echo 'description: List of Exotic class item and rolls for all classes. List may or may not be comprehensive due to some rolls being "commented out". General guidance is to *not* delete rolls that are on the "trashlist", but to use the Archive feature in DIM. Feel free to leave a PR for any changes that may or may not be accepted and merged. Thanks to Datto, Mavics, AboveDestiny, gmeiners, ATP, and Xemo for helping me form my opinions.' >> exotic-class-item-aio.txt
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo '' >> exotic-class-item-aio.txt
          echo '// ------------------------------------------------------------' >> exotic-class-item-aio.txt
          echo '// Hunter                                                      ' >> exotic-class-item-aio.txt
          echo '// ------------------------------------------------------------' >> exotic-class-item-aio.txt
          tail -n +3 hunter-exotic-class-items.txt >> exotic-class-item-aio.txt

      - name: Run a multi-line script
        run: |
          echo '' >> exotic-class-item-aio.txt
          echo '// ------------------------------------------------------------' >> exotic-class-item-aio.txt
          echo '// Titan                                                       ' >> exotic-class-item-aio.txt
          echo '// ------------------------------------------------------------' >> exotic-class-item-aio.txt
          tail -n +3 titan-exotic-class-items.txt >> exotic-class-item-aio.txt

      - name: Run a multi-line script
        run: |
          echo '' >> exotic-class-item-aio.txt
          echo '// ------------------------------------------------------------' >> exotic-class-item-aio.txt
          echo '// Warlock                                                     ' >> exotic-class-item-aio.txt
          echo '// ------------------------------------------------------------' >> exotic-class-item-aio.txt
          tail -n +3 warlock-exotic-class-items.txt >> exotic-class-item-aio.txt
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated change to generate all in one file
